package GUI;

import NapakalakiGame.Cultist;
import NapakalakiGame.CultistPlayer;
import NapakalakiGame.Player;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;

/**
 * @brief   View Cultist of MVC model
 * @file    CultistView.java
 * @author  Javier Serrano Casas
 * @date    30-05-2018
 */
public class CultistView extends javax.swing.JPanel {
    private Cultist cultistModel;

    /**
     * Creates new form CultistView
     */
    public CultistView() {
        initComponents();
        this.setVisible(false);         
    }

    public void setCultist(Player p) throws URISyntaxException{
        if (p instanceof CultistPlayer) {
            CultistPlayer cultistPlayer = (CultistPlayer) p;
            cultistModel = cultistPlayer.getMyCultistCard();
            this.setVisible(true);
            ImageIcon imgIcon = new ImageIcon(getClass().getResource(
                            "/Images/Cultist/"+cultistModel.getImage()));
            jLabel1.setIcon(imgIcon);
        } else {
            this.setVisible(false);
        }
        
        repaint();
    }        

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));
        setForeground(new java.awt.Color(0, 51, 51));

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cultist/Sectario3.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 300));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 300));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(151, 293));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cultist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
