package GUI;

import NapakalakiGame.Monster;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author serca
 */
public class MonsterView extends javax.swing.JPanel {
    private Monster monsterModel;
    
    /**
     * Creates new form MonsterView
     */
    public MonsterView() {
        initComponents();
    }

    public void setMonster(Monster m) throws URISyntaxException{
        this.monsterModel = m;
        
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(getClass().getResource("/Images/Monsters/"+monsterModel.getImage()).toURI()));
        } catch (IOException e) {
            e.printStackTrace();
        }
       
        Image dimg = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imgIcon = new ImageIcon(dimg);
        jLabel1.setIcon(imgIcon);
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new javax.swing.OverlayLayout(this));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Monsters/Familia.PNG"))); // NOI18N
        jLabel1.setOpaque(true);
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
