package GUI;

import NapakalakiGame.CombatResult;
import NapakalakiGame.Napakalaki;
import java.applet.AudioClip;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * @brief   View Napakalaki of MVC model
 * @file    NapakalakiView.java
 * @author  Javier Serrano Casas
 * @date    30-05-2018
 */
public class NapakalakiView extends javax.swing.JFrame {    
//    private final Background background;
    private Napakalaki napakalakiModel;
       
    /**
     * Creates new form Interface
     */
    public NapakalakiView() {
        initComponents();
        setTitle("Napakalaki Game");
        jButtonCombat.setText("Combat");
        jButtonNextTurn.setText("Next Turn");
        jLabel1.setText("Combat Result:");
        jButtonNextTurn.setEnabled(false);
    }

    public void setNapakalaki(Napakalaki nap) throws URISyntaxException{
        this.napakalakiModel = nap;
        this.playerView1.setNapakalaki(nap);
        this.playerView1.setPlayer(nap.getCurrentPlayer());
        this.monsterView2.setMonster(nap.getCurrentMonster());

            
        repaint();
    }
    
    public void checkPendingBadStuff() {
        if (!jLabel1.isEnabled() && napakalakiModel.nextTurnAllowed()) {
                jButtonNextTurn.setEnabled(true);
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button2 = new java.awt.Button();
        panel1 = new java.awt.Panel();
        jButtonCombat = new javax.swing.JButton();
        jButtonNextTurn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        monsterView2 = new GUI.MonsterView();
        playerView1 = new GUI.PlayerView();

        button2.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));

        panel1.setBackground(new java.awt.Color(0, 51, 51));

        jButtonCombat.setBackground(new java.awt.Color(153, 0, 153));
        jButtonCombat.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonCombat.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCombat.setText("jButton1");
        jButtonCombat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCombatActionPerformed(evt);
            }
        });

        jButtonNextTurn.setBackground(new java.awt.Color(255, 102, 102));
        jButtonNextTurn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonNextTurn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNextTurn.setText("jButton1");
        jButtonNextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextTurnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setAutoscrolls(true);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(monsterView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jButtonCombat, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jButtonNextTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(monsterView2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCombat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNextTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCombatActionPerformed
        jButtonCombat.setEnabled(false);
        checkPendingBadStuff();
        String combatresultText="";
        
        CombatResult result = napakalakiModel.developCombat();
        if (result == CombatResult.LOSE) {
            combatresultText = "Combat Result: You have LOST the combat\n";
        }
        if (result == CombatResult.LOSEANDCONVERT) {
            combatresultText = "Combat Result: You have convert a CULTIST PLAYER\n";
        }
        if (result == CombatResult.LOSEANDDIE) {
            combatresultText = "Combat Result: You have DIED\n";
        }
        if (result == CombatResult.LOSEANDESCAPE) {
            combatresultText = "Combat Result: You have ESCAPED\n";
        }
        if (result == CombatResult.WIN) {
            combatresultText = "Combat Result: You have WON the combat\n";
        }
        
        jLabel1.setText(combatresultText);

        try {
            setNapakalaki(napakalakiModel);
        } catch (URISyntaxException ex) {
            Logger.getLogger(NapakalakiView.class.getName()).log(Level.SEVERE, null, ex);
        }

        jButtonNextTurn.setEnabled(true);
     
         
        if (result == CombatResult.WINANDWINGAME) {
            JOptionPane.showMessageDialog(null, "Congratulations " + 
                napakalakiModel.getCurrentPlayer().getName() + "!!! You are the winner!!!");
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonCombatActionPerformed

    private void jButtonNextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextTurnActionPerformed
        jButtonCombat.setEnabled(true);
        jButtonNextTurn.setEnabled(false);
        String combatresultText = "Combat Result: \n";
        jLabel1.setText(combatresultText);
        
        if(!napakalakiModel.nextTurn()){
            napakalakiModel.setCanGo(false); 
            JOptionPane.showMessageDialog(null, "You can't continue because you must"
               + " discard of cards or make treasure visibles until only 4 are hidden!!!");
            jButtonCombat.setEnabled(false);
            System.exit(0);
        }

        try {
            setNapakalaki(napakalakiModel);
        } catch (URISyntaxException ex) {
            Logger.getLogger(NapakalakiView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonNextTurnActionPerformed

    /**
     * @param args the command line arguments
     */

    public void showView(String args[]) {
        setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button2;
    private javax.swing.JButton jButtonCombat;
    private javax.swing.JButton jButtonNextTurn;
    private javax.swing.JLabel jLabel1;
    private GUI.MonsterView monsterView2;
    private java.awt.Panel panel1;
    private GUI.PlayerView playerView1;
    // End of variables declaration//GEN-END:variables
}
